apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-form
  template:
    metadata:
      labels:
        app: registration-form
    spec:
      containers:
        - name: registration-form
          image: registration-form:latest  # Ensure this image is available
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: registration-service
spec:
  type: NodePort
  selector:
    app: registration-form  # Fixed selector to match Deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
